---
 - name: make sunshinesf web directory
   file:
     state: directory
     dest: /var/www/sunshinesf.org
     owner: www-data
     group: www-data
   tags:
     - sunshine

 - name: add sunshine group
   group: name=sunshine state=present
   tags:
     - sunshine

 - name: add sunshine user
   user:
     name: sunshine
     shell: /bin/false
     system: yes
     home: /srv/sunshine
     createhome: yes
     group: sunshine
   tags:
     - sunshine

 - name: deploy py-env installer
   copy:
     src: pyenv-installer.sh
     dest: /srv/sunshine/pyenv-installer.sh
     mode: 777
     owner: sunshine
     group: sunshine
   tags:
     - sunshine

 - name: install git & build-essential
   with_items:
     - build-essential
     - git
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - libssl-dev
     - zlib1g-dev
   apt:
     package: "{{ item }}"
     state: latest
     update_cache: yes
     cache_valid_time: 3600
   tags:
     - sunshine

 - name: install pyenv for sunshine
   shell: /srv/sunshine/pyenv-installer.sh
   args:
     chdir: /srv/sunshine
     creates: /srv/sunshine/.pyenv
   tags:
     - sunshine

 - name: edit .profile
   blockinfile:
     dest: /srv/sunshine/.profile
     owner: sunshine
     group: sunshine
     block: |
       export PATH="/srv/sunshine/.pyenv/bin:$PATH"
       eval "$(pyenv init -)"
       eval "$(pyenv virtualenv-init -)"
   tags:
     - sunshine

 - name: install python
   shell: su -l -c "pyenv install {{ python_version }}" -s "/bin/bash" sunshine
   args:
     chdir: /srv/sunshine
     creates: /srv/sunshine/.pyenv/versions/3.6.0/bin/python
   tags:
     - sunshine

 - name: clone sunshinesf repository
   become_user: sunshine
   git:
     repo: https://github.com/cowlicks/sunshine.git
     dest: /srv/sunshine/sunshine
     version: master
   tags:
     - sunshine

 - name: determine master HEAD
   shell: git rev-parse HEAD
   args:
     chdir: /srv/sunshine/sunshine
   register: sunshine_head
   become_user: sunshine
   tags:
     - sunshine

 - name: make release directory
   file:
     state: directory
     dest: "/srv/sunshine/www/sunshine-{{ sunshine_head.stdout }}"
     owner: sunshine
     group: sunshine
   tags:
     - sunshine

 - name: deploy archive with content at HEAD
   shell: "git archive {{ sunshine_head.stdout }} | tar -x -C /srv/sunshine/www/sunshine-{{ sunshine_head.stdout }}"
   args:
     chdir: /srv/sunshine/sunshine
   become_user: sunshine
   tags:
     - sunshine

 - name: set sunshine python version
   file:
     dest: "/srv/sunshine/www/sunshine-{{ sunshine_head.stdout }}"
     content: "{{ python_version }}"
     owner: sunshine
     group: sunshine
   tags:
     - sunshine

 - name: make symlink for latest release
   file:
     state: link
     src: "/srv/sunshine/www/sunshine-{{ sunshine_head.stdout }}"
     dest: /srv/sunshine/www/sunshine-latest
     owner: sunshine
     group: sunshine
     force: true
   tags:
     - sunshine
